### ISSUE TITLE
Error: spawn EACCES When I type something in php file

### ISSUE THREAD

**Issue by XXiao12** [AtomLinter/linter-phpmd#104]
Hello!
I have just recently downloaded Atom and got packages for php, html, css, and haskell. 
I have been working on my php file a few day ago with no error, however today this error came up. I'm not sure if I'm missing packages or if my executable PATH is not right. What does this error mean?

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at /Users/Shirleyx/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:24:53
    at /Users/Shirleyx/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:23:18
    at next (<anonymous>)
    at step (/Users/Shirleyx/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:113:191)
    at /Users/Shirleyx/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:113:368

Community packages downloaded for php:
linter-php
linter-phpcs
php-cs-fixer
php-debug

**Comment by Arcanemagus** [comment]
Hmmm, usually that error pops up when a directory is put into the executable path, instead of the full path to the executable. Generally you should be able to leave it at the default (`phpmd`) and let your system resolve it, but if that isn't working for some reason you need to specify the full path.

You can find this on your system by running `which phpmd`.

**Comment by XXiao12** [comment]
I am using a mac so would I type it in my terminal?
I got: 
usage: which [-as] program ... as the output

**Comment by XXiao12** [comment]
I also tried npm install atom-linter@~4.6.1 from another thread:
└─┬ atom-linter@4.6.1  invalid
  └── sb-promisify@1.3.0

**Comment by XXiao12** [comment]
Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at /Users/Shirleyx/.atom/packages/linter-phpmd/node_modules/sb-exec/lib/index.js:24:53
    at /Users/Shirleyx/.atom/packages/linter-phpmd/node_modules/sb-exec/lib/index.js:23:18
    at next (<anonymous>)
    at step (/Users/Shirleyx/.atom/packages/linter-phpmd/node_modules/sb-exec/lib/index.js:113:191)
    at /Users/Shirleyx/.atom/packages/linter-phpmd/node_modules/sb-exec/lib/index.js:113:368

**Comment by Arcanemagus** [comment]
That version of `atom-linter` is quite old now, run `npm update` to bring it back to what it should be!

This _should_ work just fine if you go into Settings -> Packages -> linter-phpmd and make sure the setting is on it's default value:
![image](https://cloud.githubusercontent.com/assets/427137/23002544/3246115e-f3a0-11e6-848b-f0d051099e58.png)

(The same goes for `linter-phpcs`)

**Comment by XXiao12** [comment]
It says:

Error: Failed to spawn command phpmd. Make sure phpmd is installed and on your PATH

**Comment by Arcanemagus** [comment]
Okay, that's progress at least.

What do you get when you run `which phpmd`?

**Comment by XXiao12** [comment]
Same as before 
usage: which [-as] program ...

**Comment by XXiao12** [comment]
Error: Failed to spawn command `phpmd`. Make sure `phpmd` is installed and on your PATH
    at /Users/Shirleyx/.atom/packages/linter-phpmd/node_modules/atom-linter/lib/helpers.js:102:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Arcanemagus** [comment]
Hmm, I thought I read in your first post that you already had `phpmd` installed, but on re-reading it I don't see that, which would explain all your other issues.

Have you [installed `phpmd`](https://phpmd.org/download/index.html) yet?

**Comment by XXiao12** [comment]
yes I installed it, I forgot to include phpmd in the first sentence. Linter-phpmd is phpmd right?

**Comment by Arcanemagus** [comment]
Not quite, `linter-phpmd` is a wrapper around `phpmd`, allowing it to be automatically ran and the output transformed into an output that works with the `Linter` package.

**Comment by XXiao12** [comment]
ohh I see I only installed php and the composer. How would I download phpmd? I tried the command but it did not work. Could I have installed composer wrong?

**Comment by Arcanemagus** [comment]
The page I linked to lists several different ways of installing `phpmd`, I would recommend using Composer ([installation](https://getcomposer.org/)).

I'm not sure what command you tried that didn't work, but making sure you have Composer working will probably be your first step.

**Comment by XXiao12** [comment]
Yup I followed that website to install composer and I got composer to work but the error on atom still pops up :(

**Comment by loureirorg** [comment]
Make sure to have CodeSniffer installed. Instructions for Ubuntu:
```bash
sudo apt install phpmd
sudo apt install php-pear
sudo pear install PHP_CodeSniffer
```
Then, restart Atom.
