### ISSUE TITLE
Event Reporting is not allowed at the moment. Reasons: Pre Startup or Post Shutdown

### ISSUE THREAD

**Issue by JoryHogeveen** [AtomLinter/linter-phpmd#107]
Console error:
```
linter-registry.js:144 [Linter] Error running PHPMD Error: [05.04.2017 16:08:17 NOTICE] Successfully established connection to the database 
[05.04.2017 16:08:17 NOTICE] Event Reporting is not allowed at the moment. Reasons: Pre Startup or Post Shutdown
    at ChildProcess.<anonymous> (USER\.atom\packages\linter-phpmd\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by Arcanemagus** [comment]
Does `phpmd` work on the CLI? That looks like something in your `php.ini` attempting to start a database connection 😕.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

**Comment by JoryHogeveen** [comment]
Sorry, totally forgot about this issue, if I find anything I'll reopen and report here.
