### ISSUE TITLE
error on saving gvfs mapped files

### ISSUE THREAD

**Issue by fernandopsilveira** [AtomLinter/linter-phpmd#35]
When I try to save a file on a mapped folder using gvfs, I get this:

    Error: The given file "/run/user/1000/gvfs/sftp:host=hds" does not exist.

    Error: The given file "/run/user/1000/gvfs/sftp:host=hds" does not exist.
        at exit (/home/fernando/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.coffee:33:24)
        at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
        at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by Arcanemagus** [comment]
This would be an Atom issue, this package has nothing to do with how file access it handled.

**Comment by fernandopsilveira** [comment]
That only happens when linter-phpmd is installed.

**Comment by Arcanemagus** [comment]
Does `phpmd` on the command line work on those files?

**Comment by fernandopsilveira** [comment]
outch! it doesn't...

**Comment by Arcanemagus** [comment]
Might want to file an issue [over there](https://github.com/phpmd/phpmd) then, and reference this one so anyone finding this in the future can see the status. Thanks for reporting this!
