### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by oknixus** [AtomLinter/linter-phpmd#57]
```text
Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:374:9)
    at /home/nxs/.atom/packages/linter-phpmd/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:15:53
    at Object.<anonymous> (/home/nxs/.atom/packages/linter-phpmd/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:14:18)
    at [object Generator].next (native)
    at step (/home/nxs/.atom/packages/linter-phpmd/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:84:191)
    at /home/nxs/.atom/packages/linter-phpmd/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:84:368
```

how to fix this ?
please help me ,thanks.

**Comment by stipsan** [comment]
Sounds like a permission error. Verify that the permissions on your phpmd executable match the permissions of your atom executable

**Comment by Arcanemagus** [comment]
This is actually most likely an error in the sub-dependency `sb-exec` of the `atom-linter` dependency. If you have Node.js installed can you try running `npm install atom-linter@~4.6.1` in the `linter-phpmd` directory?

**Comment by oknixus** [comment]
@Arcanemagus Thank you very much.

**Comment by Arcanemagus** [comment]
I'm going to assume that fixed your issue from the :+1: and mark this as closed, glad it helped :wink:.
